name: production-testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL}}
      BACKEND_URL: ${{secrets.BACKEND_URL}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build # Dependencies already installed
          start: npm run start # Start Next.js
          wait-on: "http://localhost:3000" # Wait for Next.js to be ready
          browser: chrome # Run tests in Chrome

